version: '3'
services:
  app:
    build: ./
    env_file: ./config/config.env 
    ports:
      - "3000:3000"
    networks:
        - storybooks-app
    depends_on:
      - db

  db:
    image: mongo:4.2
    environment:
      - MONGO_INITDB_DATABASE=storybooks
    ports:
      - "27017:27017"
    networks:
      - storybooks-app
    volumes:
      - mongodb:/data/db

networks:
  storybooks-app:
    driver: bridge

volumes:
  mongodb:
    driver: local
